ORGANIZATIONS = (
    ("Department of Administrative Reforms and Public Grievances - PG Division", "ARNPG"),
    ("Ayush", "AYUSH"),
    ("O/o the Comptroller & Auditor General of India", "CAGAO"),
    ("Central Board of Direct Taxes (Income Tax)", "CBODT"),
    ("Central Board of Indirect Taxes and Customs", "CBOEC"),
    ("Department of Atomic Energy", "DATOM"),
    ("Department of Bio Technology", "DBIOT"),
    ("Ministry of Culture", "DCLTR"),
    ("Ministry of Corporate Affairs", "DCOYA"),
    ("Department of Ex Servicemen Welfare", "DDESW"),
    ("Department of Defence Production", "DDPRO"),
    ("Department of Defence Research and Development", "DDRDO"),
    ("Banking", "DEABD"),
    ("Insurance", "DEAID"),
    ("Department of Financial Services (Pension Reforms)", "DEAPR"),
    ("Department of Justice", "DEPOJ"),
    ("Department of Fisheries", "DFSHR"),
    ("Department of Heavy Industry", "DHIND"),
    ("Health and Family Welfare", "DHLTH"),
    ("Department of Health Research", "DHRES"),
    ("Department of Legal Affairs", "DLGLA"),
    ("Department of Military Affairs", "DMAFF"),
    ("Department of Agriculture and Farmers Welfare", "DOAAC"),
    ("Department of Animal Husbandry, Dairying", "DOAHD"),
    ("Department of Agriculture Research and Education", "DOARE"),
    ("Department of Consumer Affairs", "DOCAF"),
    ("Ministry of Earth Sciences", "DOCND"),
    ("Department of Commerce", "DOCOM"),
    ("Department of Chemicals and Petrochemicals", "DOCPC"),
    ("Department of Empowerment of Persons with Disabilities", "DODAF"),
    ("Department of Investment & Public Asset Management", "DODIV"),
    ("Ministry of Drinking Water and Sanitation", "DODWS"),
    ("Department of Economic Affairs ACC Division", "DOEAF"),
    ("Department of Expenditure", "DOEXP"),
    ("Food and Public Distribution", "DOFPD"),
    ("Ministry of Food Processing Industries", "DOFPI"),
    ("Department of Fertilizers", "DOFZR"),
    ("Department for Promotion of Industry and Internal Trade", "DOIPP"),
    ("Department of Land Resources", "DOLDR"),
    ("Ministry of Development of North Eastern Region", "DONER"),
    ("Personnel and Training", "DOPAT"),
    ("Rural Development", "DORLD"),
    ("Department of Revenue", "DORVU"),
    ("Department of Science and Technology", "DOSAT"),
    ("School Education", "DOSEL"),
    ("Department of Scientific & Industrial Research", "DOSIR"),
    ("Ministry of Skill Development and Entrepreneurship", "DOSKD"),
    ("Telecommunications", "DOTEL"),
    ("Housing and Urban Affairs", "DOURD"),
    ("M/o Women and Child Development", "DOWCD"),
    ("Department of Pharmaceutical", "DPHAM"),
    ("NITI Aayog", "DPLNG"),
    ("Posts", "DPOST"),
    ("Department of Public Enterprises", "DPUBE"),
    ("Higher Education", "DSEHE"),
    ("Department of Space", "DSPAC"),
    ("Department of Sports", "DSPRT"),
    ("Ministry of Tourism", "DTOUR"),
    ("Department of Defence Finance", "FADSS"),
    ("Department of Official Language", "JSOLD"),
    ("Legislative Department", "LGVED"),
    ("Ministry of Coal", "MCOAL"),
    ("External Affairs", "MEAPD"),
    ("Home Affairs", "MINHA"),
    ("Ministry of Electronics & Information Technology", "MINIT"),
    ("Ministry of Parliamentary Affairs", "MINPA"),
    ("Ministry of Water Resources, River Development & Ganga Rejuv", "MINWR"),
    ("Ministry of Mines", "MMINE"),
    ("Ministry of Micro Small and Medium Enterprises", "MMSME"),
    ("Civil Aviation", "MOCAV"),
    ("Ministry of Cooperation", "MOCOP"),
    ("Department of Defence", "MODEF"),
    ("Ministry of Environment, Forest and Climate Change", "MOEAF"),
    ("Ministry of Information and Broadcasting", "MOIAB"),
    ("Labour and Employment", "MOLBR"),
    ("Ministry of Minority Affairs", "MOMAF"),
    ("Ministry of New and Renewable Energy", "MONRE"),
    ("Ministry of Panchayati Raj", "MOPRJ"),
    ("Railway", "MORLY"),
    ("Road Transport and Highways", "MORTH"),
    ("Department of Social Justice and Empowerment", "MOSJE"),
    ("Ministry of Statistics and Programme Implementation", "MOSPI"),
    ("Ministry of Steel", "MOSTL"),
    ("Department of Youth Affairs", "MOYAS"),
    ("Petroleum and Natural Gas", "MPANG"),
    ("Ministry of Power", "MPOWR"),
    ("Shipping", "MSHPG"),
    ("Ministry of Tribal Affairs", "MTRBL"),
    ("Ministry of Textiles", "MTXTL"),
    ("Staff Selection Commission (SSC)", "STAFF"),
    ("Unique Identification Authority of India", "UIDAI"),
)


def organization_options():
    return [{"name": name, "code": code} for name, code in ORGANIZATIONS]


def organization_by_code(code: str):
    return next((organization for organization in organization_options() if organization["code"] == code), None)