"""Add appellate_authority to UserRole and ActorRole

Revision ID: 7864d7104aea
Revises: 8b768b20f122
Create Date: 2026-08-26 17:28:59.605413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7864d7104aea'
down_revision: Union[str, None] = '8b768b20f122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE 'appellate_authority'")
    op.execute("ALTER TYPE actorrole ADD VALUE 'appellate_authority'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
