"""rbac_hierarchy_and_geo

Revision ID: 7df8047802e5
Revises: 8f70e934c7e4
Create Date: 2026-08-27 08:50:19.838741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df8047802e5'
down_revision: Union[str, None] = '8f70e934c7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grievances', sa.Column('state_code', sa.String(length=100), nullable=True))
    op.add_column('grievances', sa.Column('district_code', sa.String(length=100), nullable=True))
    
    op.execute("COMMIT")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'central_admin'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'state_admin'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'ut_admin'")
    op.execute("ALTER TYPE actorrole ADD VALUE IF NOT EXISTS 'central_admin'")
    op.execute("ALTER TYPE actorrole ADD VALUE IF NOT EXISTS 'state_admin'")
    op.execute("ALTER TYPE actorrole ADD VALUE IF NOT EXISTS 'ut_admin'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grievances', 'district_code')
    op.drop_column('grievances', 'state_code')
    # ### end Alembic commands ###
