"""Add category fields

Revision ID: 897f7765565e
Revises: 0003_add_grievance_organization
Create Date: 2026-08-26 07:47:23.413340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '897f7765565e'
down_revision: Union[str, None] = '0003_add_grievance_organization'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grievance_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.add_column('grievances', sa.Column('category_code', sa.String(length=50), nullable=True))
    op.add_column('grievances', sa.Column('parent_category_code', sa.String(length=50), nullable=True))
    op.add_column('grievances', sa.Column('category_name', sa.String(length=240), nullable=True))
    op.add_column('grievances', sa.Column('category_path', sa.Text(), nullable=True))
    op.add_column('grievances', sa.Column('category_stage', sa.Integer(), nullable=True))
    op.add_column('grievances', sa.Column('field_set_id', sa.String(length=50), nullable=True))
    op.add_column('grievances', sa.Column('category_input_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('grievances', sa.Column('destination_routing_codes', sa.Text(), nullable=True))
    op.drop_constraint('grievances_registration_id_key', 'grievances', type_='unique')
    op.create_index(op.f('ix_grievances_registration_id'), 'grievances', ['registration_id'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_grievances_registration_id'), table_name='grievances')
    op.create_unique_constraint('grievances_registration_id_key', 'grievances', ['registration_id'])
    op.drop_column('grievances', 'destination_routing_codes')
    op.drop_column('grievances', 'category_input_values')
    op.drop_column('grievances', 'field_set_id')
    op.drop_column('grievances', 'category_stage')
    op.drop_column('grievances', 'category_path')
    op.drop_column('grievances', 'category_name')
    op.drop_column('grievances', 'parent_category_code')
    op.drop_column('grievances', 'category_code')
    op.alter_column('grievance_events', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
