"""rename_district_to_district_code

Revision ID: 8f70e934c7e4
Revises: e701f1fc357b
Create Date: 2026-08-27 06:55:16.913565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f70e934c7e4'
down_revision: Union[str, None] = 'e701f1fc357b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('district_code', sa.String(length=100), nullable=True))
    op.drop_column('users', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'district_code')
    # ### end Alembic commands ###
