"""rename_state_to_state_code

Revision ID: e701f1fc357b
Revises: 7864d7104aea
Create Date: 2026-08-27 06:42:51.876177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e701f1fc357b'
down_revision: Union[str, None] = '7864d7104aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state_code', sa.String(length=100), nullable=True))
    op.drop_column('users', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'state_code')
    # ### end Alembic commands ###
